function rdifprint(data,p)

% RDIFPRINT  Prints the data generated by RDIF nicely

% Extract the number of columns
n=size(data,2);

%--------------------------------------------------------------------------
% Determine all column headers, column widths and formats
%--------------------------------------------------------------------------

if (n>=4)
    % Select basic headings
    colheadings={'k','Approximation A_h','Fraction F_h','Error estimate E_h'};
    
    % Select column wids
    wids=[6 20 12 20];
    
    % Select format specifiers
    fms={'d','.12e','.8f','.12e'};
end

if (n>=6)
    % Extend column headings
    colheadings=[colheadings, {'Error','Comparison'}];

    % Extend column wids
    wids=[wids 20 12];
    
    % Extend format specifiers
    fms=[fms, {'.12e','.8f'}];
end

% Print the data nicely
displaytable(data,colheadings,wids,fms);

% Plot the development of Richardson's fraction
plot(data(:,1),log2(abs(2^p-data(:,3)))); 

% Labels
xlabel('k'); ylabel('log_{2}(abs(2^p - F_h))');

% Grids
grid on; grid minor;